{
 "title": "NGINX Dashboard",
 "description": "Nginx,OpenResty HTTP API performance monitoring based on Prometheus LUA library",
 "tags": [ "nginx" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(nginx_request_duration_seconds_count, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "机房入口流量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "机房-状态码-QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{instance=~\"10.0.*\",host=~\"$host\"})",
     "legendFormat": "科兴-2XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_status_method_4XX{instance=~\"10.0.*\",host=~\"$host\"})",
     "legendFormat": "科兴-4XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_status_method_5XX{instance=~\"10.0.*\",host=~\"$host\"})",
     "legendFormat": "科兴-5XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{instance=~\"10.2.*\",host=~\"$host\"})",
     "legendFormat": "龙岗-2XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_status_method_4XX{instance=~\"10.2.*\",host=~\"$host\"})",
     "legendFormat": "龙岗-4XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_status_method_5XX{instance=~\"10.2.*\",host=~\"$host\"})",
     "legendFormat": "龙岗--5XX"
    }
   ]
  },
  {
   "title": "机房-域名-QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{instance=~\"10.0.*\"})  > 0",
     "legendFormat": "科兴-2xx-{{host}}"
    },
    {
     "expr": "sum by (host)(job:nginx_request_duration_seconds:qps_by_instance_host_status_method_4XX{instance=~\"10.0.*\"})",
     "legendFormat": "科兴-4XX-{{host}}"
    },
    {
     "expr": "sum by (host)(job:nginx_request_duration_seconds:qps_by_instance_host_status_method_5XX{instance=~\"10.0.*\"})",
     "legendFormat": "科兴-5XX-{{host}}"
    },
    {
     "expr": "sum by (host) (job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{instance=~\"10.2.*\"})",
     "legendFormat": "龙岗-2XX-{{host}}"
    },
    {
     "expr": "sum by (host) (job:nginx_request_duration_seconds:qps_by_instance_host_status_method_4XX{instance=~\"10.2.*\"})",
     "legendFormat": "龙岗-4XX-{{host}}"
    },
    {
     "expr": "sum by (host)(job:nginx_request_duration_seconds:qps_by_instance_host_status_method_5XX{instance=~\"10.2.*\"})",
     "legendFormat": "龙岗--5XX-{{host}}"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "3XX - 分钟",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"3..\"}[1m])) by (host)",
     "legendFormat": "3XX - 1min - {{host}}"
    }
   ]
  },
  {
   "title": "2XX QPS By Host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{host=~\"$host\"})",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_status_method_4XX{host=~\"$host\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_status_method_5XX{host=~\"$host\"})",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "错误码 4XX - 分钟",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[1m])) by (host)",
     "legendFormat": "4XX - 1min - {{host}}"
    }
   ]
  },
  {
   "title": "4XX QPS By Host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_4XX{host=~\"$host\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds_sum:err_rate_by_host{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "错误码 5XX - 分钟",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"5..\"}[1m])) by (host)",
     "legendFormat": "5XX - 1min - {{host}}"
    }
   ]
  },
  {
   "title": "5XX QPS By Host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_5XX{host=~\"$host\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "table-old",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_2XX{host=~\"$host\"}) by (host)"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"3..\"}[1m] offset 1m)) by (host)"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[1m] offset 1m)) by (host)"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"5..\"}[1m] offset 1m)) by (host)",
     "legendFormat": "5XX"
    },
    {
     "expr": "100-job:nginx_request_duration_seconds_sum:err_rate_by_host{host=~\"$host\"}"
    }
   ]
  }
 ]
}