{
 "title": "NGINX  Host",
 "description": "Nginx,OpenResty HTTP API performance monitoring based on Prometheus LUA library",
 "tags": [ "nginx" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(nginx_request_duration_seconds_count, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "入口监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "入口-QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_request_duration_seconds_count{instance=~\"10.0.*\",host=~\"$host\"}[3m])) ",
     "legendFormat": "科兴入口"
    },
    {
     "expr": "sum(rate(nginx_request_duration_seconds_count{instance=~\"10.2.*\",host=~\"$host\"}[3m])) ",
     "legendFormat": "龙岗入口"
    }
   ]
  },
  {
   "title": "入口-错误率",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_request_duration_seconds_count{host=~\"$host\",instance=~\"10.0.*\",status!~\"2..|403|304\"}[10m])) by (host) / sum(increase(nginx_request_duration_seconds_count{host=~\"$host\"}[10m])) by (host)) * 100",
     "legendFormat": "科兴入口"
    },
    {
     "expr": "(sum(increase(nginx_request_duration_seconds_count{host=~\"$host\",instance=~\"10.2.*\",status!~\"2..|403|304\"}[10m])) by (host) / sum(increase(nginx_request_duration_seconds_count{host=~\"$host\"}[10m])) by (host)) * 100",
     "legendFormat": "龙岗入口"
    }
   ]
  },
  {
   "title": "入口-ERROR",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{instance=~\"10.0.*\",host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[1m])) by(host) ",
     "legendFormat": "科兴-4XX-1min"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{instance=~\"10.0.*\",host=~\"$host\", status=~\"5..\"}[1m])) by(host) ",
     "legendFormat": "科兴-5XX-1min"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{instance=~\"10.2.*\",host=~\"$host\", status=~\"5..\"}[1m])) by(host) ",
     "legendFormat": "龙岗--5XX-1min"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{instance=~\"10.2.*\",host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[1m])) by(host) ",
     "legendFormat": "龙岗-4XX-1min"
    }
   ]
  },
  {
   "title": "入口-2XX QPS ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (job:nginx_request_duration_seconds:qps_by_instance_host_2XX{instance=~\"10.0.*\",host=~\"$host\"})",
     "legendFormat": "科兴"
    },
    {
     "expr": "sum (job:nginx_request_duration_seconds:qps_by_instance_host_2XX{instance=~\"10.2.*\",host=~\"$host\"})",
     "legendFormat": "龙岗"
    }
   ]
  },
  {
   "title": "入口-3XX - 分钟",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{instance=~\"10.0.*\",host=~\"$host\", status=~\"3..\"}[1m])) by(host) ",
     "legendFormat": "科兴-3XX-1min"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{instance=~\"10.2.*\",host=~\"$host\", status=~\"3..\"}[1m])) by(host) ",
     "legendFormat": "龙岗-3XX-1min"
    }
   ]
  },
  { "title": "机房可用性监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "机房-QPS ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host{upstream_host=~\"10.0.*\",host=~\"$host\"})",
     "legendFormat": "科兴后端"
    },
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host{upstream_host=~\"10.2.*\",host=~\"$host\"})",
     "legendFormat": "龙岗后端"
    },
    {
     "expr": "sum(rate(nginx_requests{upstream_host=~\"10.3.*\",host=~\"$host\"}[3m])) ",
     "legendFormat": "金山后端"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_requests{upstream_host=~\"10.0.*\",host=~\"$host\",status!~\"2..|403|304\"}[10m])) by (host) / sum(increase(nginx_requests{upstream_host=~\"10.0.*\",host=~\"$host\"}[10m])) by (host)) * 100",
     "legendFormat": "科兴入口"
    },
    {
     "expr": "(sum(increase(nginx_requests{upstream_host=~\"10.2.*\",host=~\"$host\",status!~\"2..|403|304\"}[10m])) by (host) / sum(increase(nginx_requests{upstream_host=~\"10.2.*\",host=~\"$host\"}[10m])) by (host)) * 100",
     "legendFormat": "龙岗入口"
    },
    {
     "expr": "(sum(increase(nginx_requests{upstream_host=~\"10.3.*\",host=~\"$host\",status!~\"2..|403|304\"}[10m])) by (host) / sum(increase(nginx_requests{upstream_host=~\"10.3.*\",host=~\"$host\"}[10m])) by (host)) * 100",
     "legendFormat": "金山入口"
    }
   ]
  },
  {
   "title": "机房-ERROR",
   "type": "graph",
   "description": "机房后端-ERROR",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host_4XX{upstream_host=~\"10.0.*\",host=~\"$host\"})",
     "legendFormat": "科兴-4XX-1min"
    },
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host_5XX{upstream_host=~\"10.0.*\",host=~\"$host\"})",
     "legendFormat": "科兴-5XX-1min"
    },
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host_5XX{upstream_host=~\"10.2.*\",host=~\"$host\"}) ",
     "legendFormat": "龙岗--5XX-1min"
    },
    {
     "expr": "sum(job:nginx_requests:qps_by_upstream_host_4XX{upstream_host=~\"10.2.*\",host=~\"$host\"})",
     "legendFormat": "龙岗-4XX-1min"
    }
   ]
  },
  {
   "title": "后端-2XX QPS ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host_2XX{upstream_host=~\"10.0.*\",host=~\"$host\"})",
     "legendFormat": "科兴"
    },
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host_2XX{upstream_host=~\"10.2.*\",host=~\"$host\"})",
     "legendFormat": "龙岗"
    },
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host_2XX{upstream_host=~\"10.3.*\",host=~\"$host\"})",
     "legendFormat": "金山"
    }
   ]
  },
  {
   "title": "后端-3XX QPS ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host_3XX{upstream_host=~\"10.0.*\",host=~\"$host\"})",
     "legendFormat": "科兴"
    },
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host_3XX{upstream_host=~\"10.2.*\",host=~\"$host\"})",
     "legendFormat": "龙岗"
    },
    {
     "expr": "sum (job:nginx_requests:qps_by_upstream_host_3XX{upstream_host=~\"10.3.*\",host=~\"$host\"})",
     "legendFormat": "金山"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "ERROR",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[1m])) by(host) ",
     "legendFormat": "4XX - 1min"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"5..\"}[1m])) by(host) ",
     "legendFormat": "5XX - 1min"
    }
   ]
  },
  {
   "title": "2XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (job:nginx_request_duration_seconds:qps_by_instance_host_2XX{host=~\"$host\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ERROR Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds_sum:err_rate_by_host_path{host=~\"$host\"} > 0.01",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_2XX{host=~\"$host\"})",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_4XX{host=~\"$host\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_5XX{host=~\"$host\"})",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "4XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_4XX{host=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX Latency(延时)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:p999_by_host_2XX{host=~\"[[host]]\"}",
     "legendFormat": "2XX-P999"
    },
    {
     "expr": "job:nginx_request_duration_seconds:p99_by_host_2XX{host=~\"[[host]]\"}",
     "legendFormat": "2XX-P99"
    },
    {
     "expr": "job:nginx_request_duration_seconds:avg_by_host_2XX{host=~\"[[host]]\"}",
     "legendFormat": "2XX-avg"
    }
   ]
  },
  {
   "title": "5XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_5XX{host=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "TOP 10 QPS",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{host=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "TOP 10 4XX over 10min",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by (path)(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"40[^3]{1}|4[^0]{1}.\"}[10m]))>0)"
    }
   ]
  },
  {
   "title": "TOP 10 5XX over 10min",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by (path)(increase(nginx_request_duration_seconds_count{host=~\"$host\", status=~\"5..\"}[10m]))>0)"
    }
   ]
  }
 ]
}