{
 "title": "NGINX  VM Host Path",
 "description": "Nginx,OpenResty HTTP API performance monitoring based on Prometheus LUA library",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "主机",
    "query": {
     "query": "label_values(nginx_process_cpu_seconds_total, hostname)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(nginx_request_duration_seconds_count, host)"
    }
   },
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(nginx_request_duration_seconds_count{host=~\"$host\"}, path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU-内存-网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate (nginx_process_cpu_seconds_total{hostname=~\"$hostname\"}[5m])) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(nginx_process_resident_memory_bytes{hostname=~\"$hostname\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "NG流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate (nginx_request_size_sum{hostname=~\"$hostname\"}[5m]))",
     "legendFormat": "Received-接收"
    },
    {
     "expr": "- sum (irate (nginx_response_size_sum{hostname=~\"$hostname\"}[5m]))",
     "legendFormat": "Sent-发送"
    }
   ]
  },
  {
   "title": "Nginx Connections",
   "type": "timeseries",
   "description": "Nginx'es connection types",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_process_connections_total{hostname=~\"$hostname\"}[5m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "错误率",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds_sum:err_rate_by_host_path{hostname=~\"$hostname\",host=~\"$host\", path=~\"$path\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "QPS by Path",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{host=~\"$host\", path=~\"$path\"}) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "$path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "fullurl" },
  {
   "title": "4XX Count（5 min）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{path=~\"[[path]]\" ,status=~\"3..\"}[5m])) by (instance)",
     "legendFormat": "3XX - {{instance}}"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{path=~\"[[path]]\", status=~\"40[^3]{1}|4[^0]{1}.\"}[5m])) by (instance)",
     "legendFormat": "4XX(with out 401 & 403) - {{instance}}"
    },
    {
     "expr": "sum(increase(nginx_request_duration_seconds_count{path=~\"[[path]]\" , status=~\"5..\"}[5m])) by (instance)",
     "legendFormat": "5XX - {{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_request_duration_seconds:p999_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "p999"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "p99"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "p90"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:avg_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "2XX QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:nginx_request_duration_seconds:qps_by_host_path_2XX{host=~\"$host\", path=~\"$path\"})",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "2XX P90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"$host\", path=~\"[[path]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX P99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"$host\", path=~\"[[path]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX P999",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:p999_by_host_instance_path_2XX{host=~\"$host\", path=~\"[[path]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2XX QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX{host=~\"$host\", path=~\"$path\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "P90 - 同比环比",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "当日-p90"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 24h > 0)",
     "legendFormat": "昨日-p90"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p90_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 7d > 0)",
     "legendFormat": "上周-p90"
    }
   ]
  },
  {
   "title": "P99 - 同比环比",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "当日-p99"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 24h > 0)",
     "legendFormat": "昨日-p99"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 7d > 0)",
     "legendFormat": "上周-p99"
    }
   ]
  },
  {
   "title": "P999 - 同比环比",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} > 0)",
     "legendFormat": "当日-p999"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 24h > 0)",
     "legendFormat": "昨日-p999"
    },
    {
     "expr": "avg(job:nginx_request_duration_seconds:p99_by_host_instance_path_2XX{host=~\"[[host]]\", path=~\"[[path]]\"} offset 7d > 0)",
     "legendFormat": "上周-p999"
    }
   ]
  }
 ]
}